# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For 7447k,=o=o=/o*= see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package Release

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Comma-separated list of packages to publish (default: all app and root dependencies)'
        required: false
        default: "@ixo/logger,@ixo/oracles-chain-client,@ixo/oracles-client-sdk,@ixo/oracles-events,@ixo/common,@ixo/matrix,@ixo/slack,@ixo/sqlite-saver,@ixo/ucan,@ixo/eslint-config,@ixo/typescript-config,@ixo/vitest-config,@ixo/oracle-runtime"
        type: string

jobs:
  publish-npm:
    # needs: [build, versioning]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies pnpm
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: |
          FILTERS=""
          IFS=',' read -ra PACKAGES <<< "${{ github.event.inputs.packages }}"
          for pkg in "${PACKAGES[@]}"; do
            FILTERS="$FILTERS --filter=$pkg"
          done
          pnpm build $FILTERS
      - name: Publish packages
        run: |
          FILTERS=""
          IFS=',' read -ra PACKAGES <<< "${{ github.event.inputs.packages }}"
          for pkg in "${PACKAGES[@]}"; do
            FILTERS="$FILTERS --filter=$pkg"
          done
          pnpm publish $FILTERS --access public --no-git-checks --provenance
